### ISSUE TITLE
windows headers

### ISSUE THREAD

**Issue by gamemachine** [nxrighthere/NanoSockets#1]
Building in VS 2019 I had to move ws2tcpip.h to the first set of includes, then just remove the address includes that were there.  in6_addr wasn't defined properly otherwise.

**Comment by nxrighthere** [comment]
Uh, that was expected. I'm not using the VS toolchain, but [LLVM-based MinGW](https://github.com/mstorsjo/llvm-mingw) to write less platform-dependent code. I will fix this soon.

**Comment by nxrighthere** [comment]
I didn't want to include the entire `ws2tcpip.h` for only two simple structure definitions in the address abstraction, but I don't see any other way to make MSVC happy...

Fixed, thanks.

**Comment by nxrighthere** [comment]
Also, I've just [fixed](https://github.com/nxrighthere/NanoSockets/commit/29bddc0e7d1b075bde25174acbd57d200cb614fa) one small typo for DLL export if you are building a shared library.
